# Generated by Django 2.2.20 on 2021-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210524_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Domain Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='screenshot',
            field=models.URLField(blank=True, default='', verbose_name='Screenshot'),
            preserve_default=False,
        ),
    ]
